### ISSUE TITLE
The codefresh badge is showing as "Build not found"

### ISSUE THREAD

**Issue by travisdowns** [nemequ/portable-snippets#23] opened 2018-08-16 04:37 UTC
At least to me as I see it in `README.md`.

It links [here](https://g.codefresh.io/repositories/nemequ/portable-snippets/builds?filter=trigger:build;branch:master;service:591f783d728f4b0001051d3e%7Eportable-snippets) which ultimately just bumps me back to the codefresh.io welcome page.

I don't know squat about codefresh so I can't help too much here...

**Comment by travisdowns** [comment] 2018-08-16 04:38
It looks like this for me:

![image](https://user-images.githubusercontent.com/2403521/44188637-46772080-a0e4-11e8-8058-529760713d3b.png)

**Comment by travisdowns** [comment] 2018-08-16 05:25
Sure, but just because you have a good system to isolate potentially breaking changes outside of master doens't really mean the CI isn't useful: I mean it still shows that in fact master is building (even though you believe that will _always_ be the case due to the way you have pushes set up, other users may not know that), and allows users to click through to see how the tests are run, what a good build looks like, whatever. Plus the badges are also just a way of saying "builds are checked on these systems" - even if the status shown is from master, you still do the builds on those systems on the other branches, so it's attesting to that.

Anyways, the Codefresh thing was more just an FYI than anything important at all.

**Comment by nemequ** [comment] 2018-08-17 01:03
> Sure, but just because you have a good system to isolate potentially breaking changes outside of master doens't really mean the CI isn't useful

CI is definitely still useful; it's used to test all the commits before they get to master.  It's just not useful to rebuild that exact same commit when it gets pushed to master. Protected branches don't let you push a commit to master unless that exact commit has already passed CI on a branch (or in a PR).

> I mean it still shows that in fact master is building (even though you believe that will always be the case due to the way you have pushes set up

The problem is I'd prefer not to build master in CI because it just wastes resources. Travis/AppVeyor/CodeFresh are providing these services for free, but it's not free for them. Seems like the least I can do is not waste their resources by building every commit twice… Unfortunately, without that second build, the status badges for master don't actually convey anything.

> Plus the badges are also just a way of saying "builds are checked on these systems" - even if the status shown is from master, you still do the builds on those systems on the other branches, so it's attesting to that.

Yeah, that's why they're there. But what they really mean is that the last time master was actually built on CI (many many commits ago) it was successful, which doesn't really match with people's expectations.  Their expectations are true that the commit would work, but they can't click through to see it… Maybe what I should do is just link to the project overview for each CI, and just show a button that always says it is working.

> Anyways, the Codefresh thing was more just an FYI than anything important at all.

Got it. Thanks, I appreciate it.

FWIW, codefresh is only for the emscripten build. GCC/clang/PGI are tested on Travis, MSVC on AppVeyor. A bunch of other compilers are also supported, including ICC, XL/C, armcc, SunCC, IAR, etc., but I haven't found a way to test them on CI (mostly because of licensing).

**Comment by travisdowns** [comment] 2018-08-17 19:53
> Yeah, that's why they're there. But what they really mean is that the last time master was actually built on CI (many many commits ago) it was successful, which doesn't really match with people's expectations. Their expectations are true that the commit would work, but they can't click through to see it…

I'm not following that part. Is `master` not the current version of the library? There might be many many other commits, but they are not really part of the library until they get the master, and master reflects what most people will use, right? Or else I am missing something...



> Protected branches don't let you push a commit to master unless that exact commit has already passed CI on a branch

I don't know exactly how your protected stuff is set up: but is it the base that a change is allowed to go to master if it was built against _exactly_ the commit of master that it will be pushed to? I assume not. For example, if you have two branches A and B they might build different changes against some version O of master and then push to master, but the second of those changes (let's say B) will actually end up in master on top of O + A, which is not what it built against, so there is a slight chance it could fail (i.e., if it conflicts with A), right?

> but it's not free for them

This is a good point!

**Comment by nemequ** [comment] 2018-08-18 14:08
> I'm not following that part. Is master not the current version of the library? There might be many many other commits, but they are not really part of the library until they get pushed to master, and master reflects what most people will use, right? Or else I am missing something...

master is the current version of the library.  Things are developed in feature branches before they are merged in to master.  For stuff that only requires a single commit (bug fixes, small features, etc.) I usually use the staging branch.

> I don't know exactly how your protected stuff is set up: but is it the base that a change is allowed to go to master if it was built against exactly the commit of master that it will be pushed to?

Yes.  The commit ID has to be tested in a branch before it reaches master, and rebasing a commit will change the ID.

The only things I can think of which can cause the build to fail in master are failures to set up the environment (e.g., a debian repository is unreachable), if the branch name is used to somehow determine the configuration at build time (it isn't), or if one of the unit tests using random values chooses a value that fails with the randomly chosen seed which happens to be used during that build.

**Comment by travisdowns** [comment] 2019-07-23 03:38
> Yes. The commit ID has to be tested in a branch before it reaches master, and rebasing a commit will change the ID.

So the branch in this case must be exactly master + the single commit in consideration, right?

Anyways, the badge seems to be working now...

**Comment by nemequ** [comment] 2019-07-23 05:19
> So the branch in this case must be exactly master + the single commit in consideration, right?

Not exactly.  There can be as many commits as you want in the branch, but the commit ID has to match.  The commit ID is a hash generated from basically everything in the commit, including the diff content, author, date/time, etc., *and the ID of the previous commit*.  Not included in that list, though, are things like repo URL and branch ID, so as long as the full history matches exactly merging one branch into another won't change the ID.

So instead of "the single commit in consideration", "all the commits in consideration".  And if the branch contains two commits you can't merge just one of them unless that exact ID has also been tested in CI without the commits that come after it.

> Anyways, the badge seems to be working now...

Yeah, I think it was just a glitch.  I'm going to close this, but we can obviously keep talking here.

**Closed by nemequ** 2019-07-23 05:19 UTC

**Comment by travisdowns** [comment] 2019-07-24 18:45
> Not exactly. There can be as many commits as you want in the branch, but the commit ID has to match. The commit ID is a hash generated from basically everything in the commit, including the diff content, author, date/time, etc., _and the ID of the previous commit_. Not included in that list, though, are things like repo URL and branch ID, so as long as the full history matches exactly merging one branch into another won't change the ID.

Right, I shouldn't have said "single commit" - what I mean is that the branch must be master + 1 or more commits, i.e., the a merge of branch to master would be a "fast forward". Another way of saying that would be that the commit ID would be the same as you point out.

That's all I was trying to get at from the beginning: the build in the branches are commits are *exactly* what will end up in master. In my A, B example above then, what happens I guess is that after A pushes, then B is no longer eligible to push until it builds against the new version of master which includes A. So it all makes sense!

I've worked on systems where this property was broken: where A  and B could separately be built on top of current master, and if they succeeded, both could push without a rebuild for the second of the two to push. It would lead to "race condition" breaks when A changes something that B needed. It was done that way because the build time * commit rate was too high to do it one-by-one: you needed that parallelism to keep up. There are other approaches too if you are wiling to throw more hardware at it (build various combinations of commits in parallel).
